# Generated by Django 4.2.7 on 2023-12-13 12:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Employee Name')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Employee Email')),
                ('address', models.TextField(max_length=500, verbose_name='Employee address')),
                ('phone', models.CharField(max_length=20, verbose_name='Employee phone')),
                ('doj', models.DateField(blank=True, default=datetime.datetime.now, verbose_name='Date of Joining')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Employee salary')),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.department')),
            ],
        ),
    ]
