# Generated by Django 4.2.7 on 2023-12-13 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=10, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.FileField(default='employee/blank.jpg', upload_to='employee', verbose_name='Employee Photo'),
        ),
    ]
